### ISSUE TITLE
Undefined Method withValues for Color in input_theme.dart

### ISSUE THREAD

**Issue by egortabula** [flyerhq/flutter_chat_ui#695]
Hello! When attempting to launch the app on an iOS simulator using the flutter_chat_core package (version 0.0.3), the following error occurs:

```
Error (Xcode): ../../.pub-cache/hosted/pub.dev/flutter_chat_core-0.0.3/lib/src/theme/input_theme.dart:61:54: Error: The method 'withValues' isn't defined for the class 'Color'.

Could not build the application for the simulator.
Error launching application on iPhone 16 Pro.
```

**Steps to Reproduce**
1. Add flutter_chat_core version 0.0.3 to pubspec.yaml.
2. Run flutter pub get.
3. Attempt to build and launch the app on an iOS simulator.

**Expected Behavior**
The app should build and launch successfully.

Environment Details

- Flutter Version: 3.24.5
- Dart Version: 3.5.4
- Device: iPhone 16 Pro simulator
- Package Version: flutter_chat_core: 0.0.3

**Pubspec.yaml**
```yaml
name: for_tests
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^5.0.0-release-candidate-9.2.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  dart_mappable: ^4.3.0
  logger: ^2.5.0
  go_router: ^14.6.2
  appwrite: 13.0.0
  isar: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  path_provider: ^2.1.5
  fpdart: ^1.1.1
  intl: ^0.19.0
  faker: ^2.2.0
  flutter_localizations:
    sdk: flutter
  skeletonizer: ^1.4.2
  cached_network_image: ^3.4.1
  logging: ^1.3.0

  # Flutter Chat
  flutter_chat_ui: ^2.0.0-dev.2
  flutter_chat_core: ^0.0.3
  flyer_chat_image_message: ^0.0.3
  flyer_chat_text_message: ^0.0.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.3.0
  isar_generator:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true

```
